import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';
import 'package:cafeplatform/model/Store.dart';

part 'store_post_response.g.dart';

@JsonSerializable()
class StorePostResponse {
  int store_id;
  String store_logo_url;
  List<String> store_photo_urls;
  PresignedUrl? presignedUrl;

  StorePostResponse(
      {required this.store_id,
      required this.store_logo_url,
      required this.store_photo_urls});

  factory StorePostResponse.fromJson(Map<String, dynamic> json) =>
      _$StorePostResponseFromJson(json);
  Map<String, dynamic> toJson() => _$StorePostResponseToJson(this);
}

@JsonSerializable()
class PresignedUrl {
  String? logo;
  List<String>? storePhoto;

  PresignedUrl({this.logo, this.storePhoto});

  PresignedUrl.fromJson(Map<String, dynamic> json) {
    logo = json['logo'];
    storePhoto = json['store_photo'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['logo'] = logo;
    data['store_photo'] = storePhoto;
    return data;
  }
}

@JsonSerializable()
class StoreCardList {
  List<StoreCard> storeList;

  StoreCardList({required this.storeList});

  factory StoreCardList.fromJson(Map<String, dynamic> json) {
    print("su>>1");
    var storeJson = json['storeList'] as List?; // List?로 nullable 처리
    return StoreCardList(
      storeList: storeJson != null
          ? storeJson
              .map((e) => StoreCard.fromJson(e as Map<String, dynamic>))
              .toList()
          : [], // null일 경우 빈 리스트 반환
    );
  }
  // factory StoreCardList.fromJson(Map<String, dynamic> json) =>
  // _$StoreCardListFromJson(json);
  Map<String, dynamic> toJson() => _$StoreCardListToJson(this);
}

@JsonSerializable()
class SearchStoreGetResponse {
  List<StoreCard> storeList;

  SearchStoreGetResponse({
    required this.storeList,
  });

  factory SearchStoreGetResponse.fromJson(Map<String, dynamic> json) =>
      _$SearchStoreGetResponseFromJson(json);
  Map<String, dynamic> toJson() => _$SearchStoreGetResponseToJson(this);
}

// class Autogenerated {
//   String? statusCode;
//   String? storeID;
//   PresignedUrl? presignedUrl;

//   Autogenerated({this.statusCode, this.storeID, this.presignedUrl});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     statusCode = json['statusCode'];
//     storeID = json['store_ID'];
//     presignedUrl = json['presigned_url'] != null
//         ? new PresignedUrl.fromJson(json['presigned_url'])
//         : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['statusCode'] = this.statusCode;
//     data['store_ID'] = this.storeID;
//     if (this.presignedUrl != null) {
//       data['presigned_url'] = this.presignedUrl!.toJson();
//     }
//     return data;
//   }
// }

@JsonSerializable()
class NaverStoreResponse {
  final String lastBuildDate;
  final int total;
  final int start;
  final int display;
  final List<StoreItem> items;

  NaverStoreResponse({
    required this.lastBuildDate,
    required this.total,
    required this.start,
    required this.display,
    required this.items,
  });

  factory NaverStoreResponse.fromJson(Map<String, dynamic> json) =>
      _$NaverStoreResponseFromJson(json);

  Map<String, dynamic> toJson() => _$NaverStoreResponseToJson(this);
}

@JsonSerializable()
class StoreItem {
  final String title;
  final String link;
  final String category;
  final String description;
  final String telephone;
  final String address;
  final String roadAddress;
  final double mapx;
  final double mapy;

  StoreItem({
    required this.title,
    required this.link,
    required this.category,
    required this.description,
    required this.telephone,
    required this.address,
    required this.roadAddress,
    required this.mapx,
    required this.mapy,
  });

  factory StoreItem.fromJson(Map<String, dynamic> json) =>
      _$StoreItemFromJson(json);

  Map<String, dynamic> toJson() => _$StoreItemToJson(this);
}
